[rabbit_mq]
url = "amqp://guest:guest@localhost:5672"
queue_name = "opentalk_mailer"

[smtp]
smtp_server = "smtp://christineannevaldez57%40gmail.com:phdnaoulbqtkdvtk@smtp.gmail.com:587"
from_name = "OpenTalk Local"
from_email = "christineannevaldez57@gmail.com"

[frontend]
base_url = "http://localhost:3000"
data_protection_url = "http://localhost:3000/dataprotection"

[monitoring]
addr = "0.0.0.0"
port = 11411
